### ISSUE TITLE
AddJob Mutation

### ISSUE THREAD

**Issue by e-leal** [e-leal/project-3#10]
When testing addJob mutation, it's not sensing a logged in user after already going through login mutation first. Almost seems like token is refreshing to undefined and not getting saved in local storage

**Comment by jesusnboone** [comment]
yeah I was running into some issues with the mutations earlier so I got off to run some errands and to take a nap. If I can't figure it out maybe we can solve the issue in class tonight since we'll have the TA's and everyone will be here.

**Comment by e-leal** [comment]
Issue was with not passing login token through http headers in graphql playground
